### ISSUE TITLE
Application should extend SpringBootServletInitializer

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/skeleton-starter-flow-spring#116]
Based on https://vaadin.com/forum/thread/17168149/17480918 : the `Application` class should extend `SpringBootServletInitializer`.

**Comment by ujoni** [comment]
The actual [Use Flow with Spring tutorial](https://vaadin.com/docs/v10/flow/spring/tutorial-spring-basic.html) (referenced in the read me) does note the need for the `SpringBootServletInitializer` extension. The code base should follow suit.
