### ISSUE TITLE
branching information in readme is misleading if project is generated in vaadin.com/start

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/skeleton-starter-flow-spring#134]
> Branching information:
master the latest version of the starter, using the latest platform snapshot
v10 the version for Vaadin 10
v11 the version for Vaadin 11
v12 the version for Vaadin 12
v13 the version for Vaadin 13

This part of readme is irrelevant and misleading for users downloading zip package from https://vaadin.com/start/latest/project-base-spring

Probably the same happens with other starters

**Comment by alejandro-du** [comment]
Since the readme file makes sense when you look at the repo, fixing this most likely requires some work from the website team as well. @gilberto-torrezan

**Comment by anasmi** [comment]
Branching information was removed from the `README.md` files. Closing the ticket due to that
