### ISSUE TITLE
Unable to shutdown spring-boot:run gracefully

### ISSUE THREAD

**Issue by paulroemer** [vaadin/skeleton-starter-flow-spring#16]
Working on Linux I am not able to stop `mvn spring-boot:run` via SIGTERM (ctrl-c)

Whole application is blocked:
```2017-11-25 21:58:02.438  INFO 14215 --- [       Thread-9] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown```

I have to kill the application with SIGKILL.

**Comment by Legioth** [comment]
Duplicate of https://github.com/vaadin/flow/issues/2871, but let's keep this issue open here as well to facilitate discoverability.
