### ISSUE TITLE
What's the advantage of using META-INF/resources?

### ISSUE THREAD

**Issue by paulroemer** [vaadin/skeleton-starter-flow-spring#17]
I am wondering about the app structure. It would be nice to have some documentation why it is as it is.

**Comment by paulroemer** [comment]
For example it would be interesting to know why there is

* META-INF/resources/etc
* META-INF/resources/index.html
* bower and NPM configuration stuff (the project is using webjars, isn't it?)

**Comment by Legioth** [comment]
Those files will be gone with https://github.com/vaadin/skeleton-starter-flow-spring/issues/7.

After that, there will only be a css file in `META-INF/resources` and a template file in `META-INF/resources/frontend`.  We might also consider moving the css file to `frontend` to keep things simple.

**Comment by tmattsso** [comment]
The current download from vaadin.com still has the front-end resources. Confirmed the project runs fine (better) without them.

**Comment by pleku** [comment]
Not valid anymore.
