### ISSUE TITLE
Add way to tell what version of starter user will download

### ISSUE THREAD

**Issue by alump** [vaadin/skeleton-starter-flow-spring#175]
https://vaadin.com/start/pre-release/project-base

If I check this page, it has absolutely now way to tell what version of starter user will download. This also applies to other versions of this.

Only thing that will give some hint is URL, but even that won't tell if what you get will be beta3 or RC1 or something else.

We are now in mess of 8, 10, 11, 12, 13, 14... and soon 15. So there should be clear indicator what user will get.

**Comment by caalador** [comment]
Well 11 and 12 are EOL so those are by default out, but this issue should be made to the website as the starter doesn't handle the site contents.

**Comment by pleku** [comment]
Opened issue for website https://gitlab.vaadin.com/vaadincom/webpage/issues/4654
