### ISSUE TITLE
Debugging in the IDE does not work (V14 RC7)

### ISSUE THREAD

**Issue by gatanaso** [vaadin/skeleton-starter-flow-spring#203]
**Description**
Debugging the "project base spring"  Vaadin 14 RC7  project does not work as per the instructions on the page:

<img width="806" alt="img1" src="https://user-images.githubusercontent.com/15094658/62282320-01b0da80-b458-11e9-83b3-9505352c228a.png">

**Actual**
Running the app in debug mode does not stop on any breakpoints.

**Expected**
Running the app in debug mode does should stop on breakpoints.

**More information**
Commenting out the `spring-boot-devtools` fixes this issues and debugging works afterwards:
```
<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-devtools</artifactId>-->
<!--            <optional>true</optional>-->
<!--        </dependency>-->
```

**Comment by Legioth** [comment]
Looks like the documentation is misleading in this case. `spring-boot:run` will in most cases cause the actual JVM to be run in a forked process, which means that the Java debugger will attach to the wrong process.

Instead, the documentation should instruct the users to run the `main` method from their IDE.

**Comment by Legioth** [comment]
There's apparently also similar instructions shown on vaadin.com/start when you download the starter from there, so we should also get those fixed.

**Comment by pleku** [comment]
Fixed with https://gitlab.vaadin.com/vaadincom/webpage-content/commit/df1a64bfe4819e7ffc5bf62fcb8bc878ee5a5262
