### ISSUE TITLE
the V15 version should use the `@PWA` annotation as well as V14

### ISSUE THREAD

**Issue by vlukashov** [vaadin/skeleton-starter-flow-spring#261]
When starting a new project from the `ccdm` branch of this repo, I want my new app to be a PWA, and include an install prompt, so that the experience and the feature set I get with Vaadin 15 is on par with that of Vaadin 14.

Also in scope: verify that the projects generated by the Starter Wizard include the `AppShell` class with the `@PWA` annotation, after this change to the `skeleton-starter-flow-spring` repo is merged.

**Comment by manolo** [comment]
This was already fixed in b3ac308619b85290774b0d9d0ec47b5b6151e481 
Tested that it works, and also the https://start.stg.vaadin.com/ wizard produces the appropriate shell and annotation.
