### ISSUE TITLE
When running mvn spring-boot:run from Eclipse the process won't terminate properly

### ISSUE THREAD

**Issue by tmattsso** [vaadin/skeleton-starter-flow-spring#29]
Terminating with any eclipse red stop buttons. 

Result is the old process taking up port 8080, and any new processes failing to start. Users can run the demo exactly once.

**Comment by SomeoneToIgnore** [comment]
You use macOs, don't you?

**Comment by tmattsso** [comment]
I do, high sierra

**Comment by tmattsso** [comment]
Eclipse version is 'Version: Oxygen.2 Release (4.7.2)'

**Comment by ZheSun88** [comment]
I think maybe i can add it here too... 

I cannot terminate the port properly, with git bash and Eclipse on windows... maybe related or not..
related link https://vaadin.slack.com/archives/C6RAXJATF/p1515078880000047

**Comment by Legioth** [comment]
Based on my experience, you should usually run the `main` method instead of running as a Maven step when using Eclipse. I don't even think this is specific to this starter or even Flow, but rather a general gotcha with `spring-boot:run`.

**Comment by tmattsso** [comment]
Could be, but that should be said in the instructions at the very least.

**Comment by pleku** [comment]
This could be added as a _Note_  to the readme's in this starter and in Flow Spring Tutorial.

**Comment by enver-haase** [comment]
Maybe #371 would fix this issue here, too?  (setting fork mode to false)
