### ISSUE TITLE
Feature(?) Request: Support DEBUG for spring-boot:run in IDEA by setting fork=false

### ISSUE THREAD

**Issue by enver-haase** [vaadin/skeleton-starter-flow-spring#371]
Setting the fork mode to false like
```
 <build>
        <defaultGoal>spring-boot:run</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <!-- Clean build and startup time for Vaadin apps sometimes may exceed
                     the default Spring Boot's 30sec timeout.  -->
                <configuration>
                    <wait>500</wait>
                    <maxAttempts>240</maxAttempts>
                    <fork>false</fork>
                </configuration>
            </plugin>
```
allows to right-click Maven->spring-boot:run and "Debug" out of the box, otherwise the JAR needs to be run via its main() method.

Version is:
 <vaadin.version>14.2.1</vaadin.version>

**Comment by enver-haase** [comment]
Oh, and here: https://vaadin.com/learn/training/v14-intro at 3:40 @OlliTietavainenVaadin talks about the debug mode that does not work without the above change.

**Comment by mstahv** [comment]
A direct quote from the Spring Boot documentation: 

> Although this is not recommended, it is possible to execute the application directly from the Maven JVM by disabling the fork property.

The suggested way to run applications (by the Spring developers) during the development is to run the main method of the application directly from the IDE. We should always guide people towards that habit as well.

**Comment by enver-haase** [comment]
That's a good idea. Please can you fix that in README.md which wrongly guides people to use spring-boot:run .

**Comment by mstahv** [comment]
👍 That should indeed be clearly mentioned in the docs that Running the main method is the primary way and spring-boot:run is more for command line testing.
