### ISSUE TITLE
Feature Request: put the @Route annotated view in another package, introduce @EnableVaadin

### ISSUE THREAD

**Issue by enver-haase** [vaadin/skeleton-starter-flow-spring#372]
This feature, albeit documented, cost me way more than an hour to understand and fix.
It is not easy to see why some @Route - annotated are entirely ignored by the system.

So please can you restructure the demo app, have the view in some 'view' package and introduce the @EnableVaadin annotation?  Thanks.

**Comment by samie** [comment]
Not completely sure, if I'm understood this one correctly, but I think there was something related to startup speed to limit the scanning.

Was your use case to rename the package? Or adding an another view? Or something else?

**Comment by enver-haase** [comment]
I added a package where I wanted to put the views, to separate them from the business logic.
The 'XxxApplication' was saved into a 'main' package; different from the 'view' package.

Goal was to deepen the project tree structure to allow for more classes and code without becoming untidy.

**Comment by simasch** [comment]
I don't like this idea because I prefer to use the defaults of Spring Boot. Which means having the Spring Boot Application in the root and everything bellow in the tree.

**Comment by enver-haase** [comment]
Maybe document it in the starter app then, for the case people are moving the view packages. This has cost me hours, why shouldn't that happen to others.

**Comment by simasch** [comment]
This is a Spring Boot topic and not directly related to Vaadin.

If you move for example a repository out of the hierarchy Spring Data will not find it.

**Comment by enver-haase** [comment]
I think if you create a caravan from a Fiat Ducato you should include its manual in the glovebox rather than pointing to the Fiat website.

**Comment by enver-haase** [comment]
My point was "introduce @EnableVaadin early in the learning process" which is not a Spring issue even.

**Comment by simasch** [comment]
Using @EnableVaadin should be an exception. I only use it if I have common components or themes in an external dependency.

Again as a Spring Boot developer is the same with @EnableJpaRepository, @ComponentScan, @EnableTransactionManagement all things that come out of the box if you follow the defaults.

**Comment by enver-haase** [comment]
While I do get your point (I wasn't even aware of some @EnableXXX SpringBoot pattern) I think this shows the dilemma. The default starter app is so closely tied to SpringBoot that we're expecting people to have at least intermediate knowledge of that technology. I think we should not for a very first glimpse at Vaadin.

**Comment by simasch** [comment]
Don't get me wrong - indeed it may be helpful. 

But @EnableVaadin is not even mentioned in the Vaadin documentation: https://vaadin.com/docs/v21/flow/integrations/spring/spring-boot

Maybe we should add it there and just have a link to the documentatoin

**Comment by enver-haase** [comment]
It should be documented somewhere, maybe in Vaadin-Spring?   Yes, a comment would be all that is needed to spare some people bad out of the box DX.

**Comment by simasch** [comment]
There is already a link in the README.

Also for people new to Spring Boot a link to the Spring Boot documentation, especially this the following section, could be helpful https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.structuring-your-code

**Comment by Artur-** [comment]
The point of the starter is to get started, not to show potential configuration options so let's not complicate it just for the fun of it
