### ISSUE TITLE
Feature(?) Request: Fix README.md to guide people run the Main method rather than spring-boot:run

### ISSUE THREAD

**Issue by enver-haase** [vaadin/skeleton-starter-flow-spring#375]
See #371 for the reasoning.

**Comment by simasch** [comment]
I'm not sure if this is better. 
Using spring-boot:run will not require any IDE to just run the app.

**Comment by enver-haase** [comment]
It does not need a debugger for running either, but using a debugger while developing is strongly advised.

**Comment by simasch** [comment]
Sure so probably both ways should be mentioned.
