### ISSUE TITLE
"You can use .css files too" in shared-styles.html is uninformative

### ISSUE THREAD

**Issue by Artur-** [vaadin/skeleton-starter-flow-spring#52]
How do you use css files? "It's inside some strange `<custom-style>` tag"

**Comment by pleku** [comment]
Should be clarified to how/where

**Comment by Artur-** [comment]
The comment is in `shared-styles.html` so maybe there

**Comment by pleku** [comment]
I meant that clarified in the code where you use your `styles.css` instead of just saying you can use something somewhere

**Comment by anasmi** [comment]
With the "re-write", there are now two style files : `shared-styl.css` and a separate one for the textField. 
Assuming that the change has addressed the problem, closing the issue.
