### ISSUE TITLE
Add starter to vaadin.com/start

### ISSUE THREAD

**Issue by pleku** [vaadin/skeleton-starter-flow-spring#6]
There is also vaadin/skeleton-starter-flow#37 for the same thing, can be done together.

Need to fork the website and add the Starter there manually. Here is an example on doing the same for Beverage Buddy Starter: https://gitlab.vaadin.com/vaadincom/webpage/commit/6f267171d3883531dc9bd4111c9f6f9f57420ad2
The latest version of the starter should also be tagged with `published` tag to get it visible on the website.

**Comment by denis-anisimov** [comment]
https://gitlab.vaadin.com/vaadincom/webpage/merge_requests/134
https://gitlab.vaadin.com/denis/webpage/commit/dcf823ea7488708dbf305b456fdbe4e72f68f127
