### ISSUE TITLE
The project should create jar file

### ISSUE THREAD

**Issue by mstahv** [vaadin/skeleton-starter-flow-spring#72]
Jar packaging is the primary method for spring boot apps and we should support Spring here. If somebody still for some reason needs war file he can change the project easily for that using Spring's documentation (which is also different of how war is created here).

**Comment by anasmi** [comment]
This should have been fixed by https://github.com/vaadin/skeleton-starter-flow-spring/pull/77 . Closing the issue.

Please, ping us, if you thing that issue is not fully addressed
