### ISSUE TITLE
fix the validation build on dev mode 

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/skeleton-starter-flow-spring#843]
since Vaadin 23.2.0.beta3, we switched to use vite as a primary tool. 

the dev-mode validation failed as 
```
page crash 
Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES`
```

we need to fix this.

**Comment by Artur-** [comment]
Did you fix this?

**Comment by mshabarov** [comment]
@ZheSun88 can you please give a link to the failing build if any?

**Comment by ZheSun88** [comment]
seems cannot reproduce any more.. 
let us close it then.
