### ISSUE TITLE
Third party web components do not work

### ISSUE THREAD

**Issue by priandsf** [vaadin/skeleton-starter-flow-spring#874]
Hello - I'm using the [XTerm add on](https://vaadin.com/directory/component/xterm-console-addon). I got it to work properly with the plain java starter, but can't make it work with the spring boot one. Actually, the component is executed but the client side code (web component) is not referenced in the dependencies and not thus loaded in the bundle.
I put a quick example [here](https://github.com/priand/vaadin-xterm-issue) using start.vaadin.com. I injected some sample XTerm code in it. @javier-godoy

**Comment by javier-godoy** [comment]
Hello. For spring-boot applications you need to whitelist the addon package.
Please add `com.flowingcode` [here](https://github.com/priand/vaadin-xterm-issue/blob/main/src/main/resources/application.properties#L9)
```vaadin.whitelisted-packages = com.vaadin,org.vaadin,dev.hilla,com.example.application,com.flowingcode```

See https://github.com/FlowingCode/XTermConsoleAddon/issues/40

**Comment by priandsf** [comment]
Thank you @javier-godoy, that fixed the problem!
If this makes sense when you know how it works, this is hard to figure out when you miss this knowledge. If wondering if this can be checked and reported in dev mode, with an explicit message.
